HOST = 0.0.0.0
PORT = 5000
PROJECT_NAME=lbc2rss
APP_PATH = $(PWD)/$(PROJECT_NAME)

export FLASK_APP = $(PROJECT_NAME)
export FLASK_ENV=development
export APP_LOG=$(PROJECT_NAME).log
export APP_SETTINGS=$(PROJECT_NAME).config.DevelopmentConfig

PYTHON_VERSION ?= python3
VENV = $(PWD)/.venv
PIP = $(VENV)/bin/pip
PYTHON = $(VENV)/bin/python
PYTEST = $(VENV)/bin/py.test
FLASK = $(VENV)/bin/flask
GUNICORN = $(VENV)/bin/gunicorn
ISORT = $(VENV)/bin/isort
BLACK = $(VENV)/bin/black
MYPY = $(VENV)/bin/mypy
